//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootShot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProject
    {
        public int fId { get; set; }
        public string fOrderNum { get; set; }
        public Nullable<System.DateTime> fPjtDate { get; set; }
        public string fCEmail { get; set; }
        public string fContact { get; set; }
        public string fContactTel { get; set; }
        public string fWkdyTime { get; set; }
        public string fWkndTime { get; set; }
        public string fCity { get; set; }
        public string fLoc { get; set; }
        public Nullable<System.DateTime> fFilmDate { get; set; }
        public Nullable<System.TimeSpan> fFilmTime { get; set; }
        public Nullable<int> fBudget { get; set; }
        public Nullable<int> fPrintQty { get; set; }
        public string fPjtTopic { get; set; }
        public string fReq { get; set; }
        public string fStyle { get; set; }
        public Nullable<bool> fPjtState { get; set; }
        public string fPEmail { get; set; }
    }
}
