//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootShot
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAlbumPhoto
    {
        public int fId { get; set; }
        public Nullable<int> fAlbId { get; set; }
        public string fName { get; set; }
        public string fDes { get; set; }
        public Nullable<bool> fCover { get; set; }
        public Nullable<int> fLike { get; set; }
        public Nullable<int> fView { get; set; }
        public string fKeyword { get; set; }
    }
}
