//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootShot
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMsg
    {
        public int fId { get; set; }
        public string fOrderNum { get; set; }
        public string fPEmail { get; set; }
        public Nullable<System.DateTime> fPMsgTime { get; set; }
        public string fPMsg { get; set; }
        public string fCEmail { get; set; }
        public Nullable<System.DateTime> fCMsgTime { get; set; }
        public string fCMsg { get; set; }
        public Nullable<bool> fStates { get; set; }
    }
}
