//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootShot.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        public int fId { get; set; }
        [Required(ErrorMessage = "請輸入姓名")]
        public string fName { get; set; }
        public string fPhoto { get; set; }
        public Nullable<System.DateTime> fBday { get; set; }
        [Required(ErrorMessage = "請輸入電子郵件")]
        public string fEmail { get; set; }
        [Required(ErrorMessage = "請輸入電話")]
        public string fTel { get; set; }
        public string fArea { get; set; }
        [Required(ErrorMessage = "請輸入密碼")]
        public string fPassword { get; set; }
        [Required(ErrorMessage = "請輸入性別")]
        public Nullable<int> fGender { get; set; } 
        public Nullable<int> fCode { get; set; }
    }
}
